export type Category = {
  id: number;
  name: string;
  color?: string;
  _count?: {
    expenses: number;
  };
};

export type Expense = {
  id: number;
  amount: string;
  date: string;
  description?: string;
  categoryId: number;
  category: Category;
  createdAt: string;
  updatedAt: string;
  // Recurring transaction fields
  recurringTemplateId?: number;
  recurringTemplate?: RecurringTemplate;
  isAutoGenerated: boolean;
};

export type Income = {
  id: number;
  amount: string;
  date: string;
  description?: string;
  createdAt: string;
  updatedAt: string;
  // Recurring transaction fields
  recurringTemplateId?: number;
  recurringTemplate?: RecurringTemplate;
  isAutoGenerated: boolean;
};

export type Transaction = {
  id: number;
  amount: string;
  date: string;
  description?: string;
  createdAt: string;
  updatedAt: string;
  type: 'expense' | 'income';
  category?: Category; // Only for expenses
  categoryId?: number; // Only for expenses
  // Recurring transaction fields
  recurringTemplateId?: number;
  recurringTemplate?: RecurringTemplate;
  isAutoGenerated: boolean;
};

export type RecurringType = 'EXPENSE' | 'INCOME';

export type Frequency = 'WEEKLY' | 'MONTHLY' | 'YEARLY';

export type RecurringTemplate = {
  id: number;
  type: RecurringType;
  amount: string;
  description?: string;
  categoryId?: number; // Only for expenses
  category?: Category;
  frequency: Frequency;
  interval: number;
  startDate: string;
  endDate?: string; // For installments
  nextDueDate: string;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
};

export type RecurringTemplateFormData = {
  type: RecurringType;
  amount: number;
  description?: string;
  categoryId?: number;
  frequency: Frequency;
  interval: number;
  startDate: Date;
  endDate?: Date;
  isActive: boolean;
};
